site_name: RetroAchievements docs 
site_description: RetroAchievements.org Documentation Project 

repo_name: RetroAchievements/docs
repo_url: https://github.com/RetroAchievements/docs/wiki/
# XXX: If you do not want any "edit URL link" displayed on your pages,
# then set edit_uri to an empty string to disable the automatic setting.
edit_uri: https://retroachievements.org/wiki-edit-redirect.php?page=

docs_dir: docs.wiki

theme:
    name: material
    palette:
        primary: 'grey'
        accent: 'amber'
    logo:
        icon: 'videogame_asset'
    favicon: 'img/favicon.ico'
    # XXX: using custom_dir in order to change the footer
    custom_dir: 'theme'

#extra_css:
#    - 'css/extra.css'
#    - 'css/extra.scss'

# XXX: testing icons on footer
extra:
  social:
    - type: globe
      link: https://retroachievements.org/
    - type: discord
      link: https://discord.gg/dq2E4hE
    - type: github-alt
      link: https://github.com/RetroAchievements

# strict 
# Determines if a broken link to a page within the documentation is considered 
# a warning or an error (link to a page not listed in the pages setting). Set 
# to true to halt processing when a broken link is found, false prints a warning 
#strict: true

# dev_addr 
# Determines the address used when running mkdocs serve. 
# Must be of the format IP:PORT. 
dev_addr: '0.0.0.0:8000'

